### PR TITLE
Updated-Interactive-list

### PR DESCRIPTION
**Pull request by gilberthappi**
Use webpack to bundle JavaScript.
Learn how to use proper ES6 syntax.
Use ES6 modules to write modular JavaScript.

### CODE REVIEW

**Review by usorfaitheloho — APPROVED** [review]
Hi @gilberthappi  , 
# STATUS: APPROVED! 🥇 💯 

done

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Please when submitting a project for re-review, try not to create a new PR as it'd help the reviewer to keep track of the suggested changes by previous reviewers



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by medaminedev66** [comment]
Hi @gilberthappi, 
### This is a manual review
# Request Changes ♻️

We apologize for the mistake made by the previous Code Reviewer, @usorfaitheloho. Your project is not complete, and the PR should not have been approved.

As per the requirements, the user should be able to clear all completed tasks. Please note that when the user clicks on the 'Clear all completed' button, all tasks with the 'completed' value set to true should be removed. Additionally, a function for the 'Clear all completed' button using the Array.filter() method should be implemented to achieve this.

Furthermore, users should have the capability to add and remove books to enhance the user experience. After the  user clears all completed tasks, new tasks should be added to assess whether the app functions as expected.
 
Cheers and Happy coding!:clap::clap::clap:

**Comment by enniopo** [comment]
Hi @gilberthappi - I have changed the activity´s status on your dashboard so you can submit another code review request as soon as you are done implementing all the necessary changes. 
Once again, apologies for any inconvenience caused.

**Comment by enniopo** [comment]
Hi @gilberthappi - please disregard both my and @medaminedev66's comments.
We saw you implemented the changes requested into another PR but then used this one to request the changes. That´s what caused the misunderstanding. 

I have now approved your project again. No other actions are needed from your side.

**Comment by gilberthappi** [comment]
Okey Thanks
Reset  the activity´s status on my dashboard

**Pull request merged**
